package com.acm.dijkstrasden;

public enum NotifyTypeEnum {
	NOTIFY_LEVELSTART,
	NOTIFY_BUMP, 
	NOTIFY_ATNODE, 
	NOTIFY_ORIENT, 
	NOTIFY_MOVE, 
	NOTIFY_LEVELDONE, 
	NOTIFY_NONE, 
	NOTIFY_STOPSOUND,
	NOTIFY_GAMEDONE
}